### ISSUE TITLE
这里是不是应该是codec 

### ISSUE THREAD

**Issue by shinwing** [megaredfan/rpc-demo#1]
https://github.com/megaredfan/rpc-demo/blob/75bcfc0fdb4295ef66748d3f7eec41bc568f72c0/protocol/protocol.go#L129

应该用codec吧？

**Comment by megaredfan** [comment]
这里是对header部分进行序列化，在我们设计的消息协议中，一个消息分为header和body部分，body部分通过codec序列化，至于codec的具体实现有header里的SerializeType属性决定。但是header自己也是需要被序列化的，header的序列化到底使用哪种实现呢？这怎么决定呢？这里简单起见我就直接使用msgpack了，也就是说我们的消息协议里规定header用msgpack序列化，body由header中的信息指定的序列化方式进行序列化

**Comment by shinwing** [comment]
明白，我是觉得这里好像有点不方便了。譬如header在mp编码的情况下，一般会给body指定其他的type么？

**Comment by megaredfan** [comment]
header部分用mp编码，这实际上对用户是不可见的也是不可配置的。而body部分用户可以在构造客户端或者服务端时显示指定，当然默认也是mp。。

**Comment by shinwing** [comment]
明白了，这里和我理解的不太一样。我原先理解的client可能是其他语言实现的，用的不一定是这里的client。 多谢回复。
